### model
model_name_or_path: sapienzanlp/Minerva-7B-base-v1.0  # no hf_id but the absolute path, save it in a specific directory
new_special_tokens: <|start_header_id|>,<|end_header_id|>,<|eot_id|>  # token added with the chat template

### method
stage: sft  # Supervised Fine-Tuning
do_train: true
finetuning_type: full
use_badam: true  # use BADAM not classical full-finetuning, faster!
badam_mode: layer
badam_switch_mode: ascending
badam_switch_interval: 50
badam_verbose: 2
flash_attn: fa2
deepspeed: examples/deepspeed/ds_z3_config.json  # deepspeed

### dataset
dataset: magpielm-v0.1  # comma separated datasets, defined in: data/dataset_info.json
template: llama3  # chat_template
cutoff_len: 2048
max_samples: 560000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /minerva_7b_instruct  # output directory
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
learning_rate: 5e-5
num_train_epochs: 8
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: False
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 100

### logging
report_to: wandb
run_name: mnlp_hw2  # the name of the run